version: '3.8'
services:
  django:
    container_name: django
    build:
      context: ./core
    command: uvicorn core.core.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level debug --reload
    volumes:
      - ./core:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./env_vars_django.txt
    # depends_on:
    #   - redis